{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "folia-api",
    "version": "1.21.4-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.4-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.20-R0.2-deprecated+build.19"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.4-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.4-R0.1-SNAPSHOT.jar",
          "size": 2533205,
          "sha512": "e83eee516e2383c18303c5658fcf2b3f562daf3f6ec593abbe14d6f1ae8b538ccb2b5e67f737b6ee6e3de5f144ac90847cacf064a740c6ae0d62a220935c9733",
          "sha256": "da0f9a19e84fde5987579adea92e6e18f77f9c5ce1b9c3128036bcf1f9e748cc",
          "sha1": "77b9e5eeb09ed7098bb10a41421c9c05d1cba6cf",
          "md5": "13570f44791069e6a5b814999513d8ba"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.4-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.4-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.20-R0.2-deprecated+build.19"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.4-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.4-R0.1-SNAPSHOT.jar",
          "size": 2533205,
          "sha512": "e83eee516e2383c18303c5658fcf2b3f562daf3f6ec593abbe14d6f1ae8b538ccb2b5e67f737b6ee6e3de5f144ac90847cacf064a740c6ae0d62a220935c9733",
          "sha256": "da0f9a19e84fde5987579adea92e6e18f77f9c5ce1b9c3128036bcf1f9e748cc",
          "sha1": "77b9e5eeb09ed7098bb10a41421c9c05d1cba6cf",
          "md5": "13570f44791069e6a5b814999513d8ba"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.4-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.4-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.4-R0.1-SNAPSHOT-sources.jar",
          "url": "folia-api-1.21.4-R0.1-SNAPSHOT-sources.jar",
          "size": 1834352,
          "sha512": "d69ff80082d160070a3b784c1289702bc964da3581da7be41aabb1c39844d73c10245232d3ac477e0c035ad341df731b990b08e25e748dd22e92f14d20a7e1e9",
          "sha256": "f624c360c32056fe0b64b14fae569bbefa665ebfa069de510fd4f7a7c1ccd4a0",
          "sha1": "01d044b8f75bd7caef9d631e31c27b377514fa17",
          "md5": "21622fcecaa7879fddf70230562af466"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.4-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.4-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.4-R0.1-SNAPSHOT-javadoc.jar",
          "url": "folia-api-1.21.4-R0.1-SNAPSHOT-javadoc.jar",
          "size": 14657312,
          "sha512": "30fa1755c8b959d17a9a2c9a78a9d30c24237c087f2fa4c0cfd0cdd50b71295128300e8d608b6c8f707af9e07941e195df324e40b6e4a526f2c361ebb3aabdfd",
          "sha256": "4ddcc6e6b310a0839dd77d749a1efbbc5d07220bafa82e3700d0ded1eaf27c46",
          "sha1": "3d6649392c5187f11f7a9a58eca994c3761248a9",
          "md5": "57a73b590f28b59aea123378fad9e2c3"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.4-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.4-R0.1-SNAPSHOT"
        }
      ]
    }
  ]
}
